---
title: "textual analysis"
author: "Sudha Muppala"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true
    theme: flatly
    highlight: haddock
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Medical Analysis for Breast cancer detection

```{r}
#Loading required libraries
library(caret)
library(tidyverse)
library(knitr)
library(ggplot2)
library(naniar)
library(GGally)
```

```{r}
#Loading the breast cancer dataset
cancer_data<-read_csv("Cancer_Data.csv")

```

```{r}
#Provide summary of the dataset
summary(cancer_data)
```

```{r}
#Plot pairwise relationships in selected columns
cancer_data %>% 
  select(radius_mean, texture_mean,perimeter_mean,area_mean, diagnosis) %>% 
  drop_na() %>% 
  ggpairs()
```

```{r}
# scatter plots for selected features to analyse the dataset
ggplot(cancer_data, aes(symmetry_mean,fractal_dimension_mean, col=diagnosis, shape=diagnosis)) + 
  geom_point() + 
  ggtitle("cancer scatter plot")
ggplot(cancer_data, aes(radius_mean,texture_mean, col=diagnosis, shape=diagnosis)) + 
  geom_point() + 
  ggtitle("cancer scatter plot")

```

```{r}
#preprocessing data 
#converting diagnosis to a factor
cancer_data$diagnosis <- as.factor(cancer_data$diagnosis)
# removing extra column preset in the data set
cancer_data <- cancer_data[, -33] 
#Calculate the correlation between raduis_mean and testure_mean
cor(cancer_data$radius_mean,cancer_data$texture_mean)

```

```{r}
set.seed(1234)



#Split the dataset into train and test set 
sample_index<- createDataPartition(cancer_data$diagnosis, p=0.7, list=FALSE)
train_set <- cancer_data[sample_index,-1 ]
test_set <- cancer_data[-sample_index,-1 ]

#Define training control parameters for cross-validation
train_control<-trainControl(method="cv",
                             number=5,
                             preProcOptions=list(thres=0.99),
                             classProbs=TRUE,
                             summaryFunction=twoClassSummary)
#train the random forest model using the 'ranger' method
model<- train(diagnosis~., train_set, method="ranger", trControl= train_control)

```

```{r}
#making predictions on the test dataset
prediction_rf <- predict(model, test_set)


#Generating a confusion matrix to evaluate the model's performance
cm_rf <- confusionMatrix(prediction_rf, test_set$diagnosis, positive = "M")
cm_rf
```

```{r}
#Perform PCA on the data
pca_data<-prcomp(cancer_data%>% select(-id, - diagnosis), scale=TRUE, center=TRUE)

summary(pca_data)
```

```{r}
#converting PCA results to tibble for plotting
pca_df<- as_tibble(pca_data$x)
#Ploting PCA results with first two principle components
ggplot(pca_df, aes(x=PC1,y=PC2, col=cancer_data$diagnosis))+geom_point()
```
